# Generated by Django 2.1.7 on 2019-03-26 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0001_initial'),
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='選舉類型')),
                ('department', models.ManyToManyField(to='school.Department', verbose_name='可參與科系')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='電子郵件')),
                ('is_agree', models.BooleanField(default=True, verbose_name='同意票')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='投票時間')),
                ('candidate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='candidates.Candidate', verbose_name='候選人')),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elections.Pool', verbose_name='投票類型')),
            ],
        ),
    ]
