# Generated by Django 2.1.7 on 2019-03-26 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('email', 'pool')},
        ),
    ]
