# Generated by Django 2.1.7 on 2019-03-26 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0002_auto_20190327_0138'),
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField(verbose_name='開始時間')),
                ('end_at', models.DateTimeField(verbose_name='結束時間')),
            ],
        ),
    ]
