# Generated by Django 2.1.7 on 2019-03-27 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0004_auto_20190327_1107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pool',
            old_name='department',
            new_name='departments',
        ),
    ]
