# Generated by Django 2.1.7 on 2019-03-27 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0005_auto_20190327_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidates.Candidate', verbose_name='候選人'),
        ),
    ]
