# Generated by Django 2.1.7 on 2019-04-14 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0006_auto_20190327_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='std_no',
            field=models.CharField(default='', max_length=15, verbose_name='學號'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('std_no', 'pool')},
        ),
    ]
