# Generated by Django 2.1.7 on 2019-04-14 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0008_remove_vote_email'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='vote',
            name='pool',
        ),
    ]
