# Generated by Django 2.2.1 on 2019-05-04 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_group_student'),
        ('elections', '0010_auto_20190426_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='pool',
            name='groups',
            field=models.ManyToManyField(to='school.Group', verbose_name='可參與群組'),
        ),
    ]
