# Generated by Django 2.2.1 on 2019-05-06 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0011_pool_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pool',
            name='departments',
            field=models.ManyToManyField(blank=True, to='school.Department', verbose_name='可參與科系'),
        ),
        migrations.AlterField(
            model_name='pool',
            name='groups',
            field=models.ManyToManyField(blank=True, to='school.Group', verbose_name='可參與群組'),
        ),
    ]
