# Generated by Django 2.2.1 on 2019-05-07 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0012_auto_20190506_1845'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pool',
            options={'verbose_name': '選舉類型', 'verbose_name_plural': '選舉類型'},
        ),
    ]
