# Generated by Django 2.2.1 on 2019-05-07 04:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0013_auto_20190507_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pool',
            name='name',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^.*(會長|議員|代表)$')], verbose_name='選舉類型'),
        ),
    ]
