# Generated by Django 2.2.1 on 2019-05-07 16:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0015_auto_20190507_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pool',
            name='name',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='必須是會長、議員或學生代表結尾', regex='^.*(會長|議員|學生代表)$')], verbose_name='選舉類型'),
        ),
    ]
