# Generated by Django 2.2.1 on 2021-06-10 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_system'),
        ('elections', '0016_auto_20190508_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='pool',
            name='systems',
            field=models.ManyToManyField(blank=True, to='school.System', verbose_name='可參與學制'),
        ),
    ]
