# Generated by Django 2.2.1 on 2021-06-10 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0017_pool_systems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pool',
            name='systems',
            field=models.ManyToManyField(to='school.System', verbose_name='可參與學制'),
        ),
    ]
