# Generated by Django 2.1.7 on 2019-03-26 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('elections', '0001_initial'),
        ('candidates', '0001_initial'),
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='pool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='elections.Pool', verbose_name='選舉類型'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school.System', verbose_name='學制'),
        ),
    ]
