# Generated by Django 2.1.7 on 2019-03-27 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_auto_20190327_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='pool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='candidates', to='elections.Pool', verbose_name='選舉類型'),
        ),
    ]
