# Generated by Django 2.1.7 on 2019-03-27 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0003_auto_20190327_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='politics',
            field=models.TextField(blank=True, max_length=1000, verbose_name='政見'),
        ),
    ]
