# Generated by Django 2.1.7 on 2019-04-13 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0006_auto_20190327_1432'),
        ('candidates', '0004_auto_20190327_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='name',
            field=models.CharField(default='', max_length=30, verbose_name='姓名'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='std_no',
            field=models.CharField(default='', max_length=15, verbose_name='學號'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='candidate',
            name='klass',
            field=models.CharField(max_length=30, verbose_name='課程'),
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='department',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='system',
        ),
        migrations.AlterUniqueTogether(
            name='candidate',
            unique_together={('std_no', 'pool')},
        ),
    ]
