# Generated by Django 2.2 on 2019-04-26 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0005_auto_20190414_0043'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidate',
            options={'verbose_name': '候選人', 'verbose_name_plural': '候選人'},
        ),
    ]
