# Generated by Django 2.1.7 on 2019-04-13 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0005_auto_20190414_0043'),
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Class',
        ),
        migrations.DeleteModel(
            name='Grade',
        ),
        migrations.DeleteModel(
            name='System',
        ),
    ]
