# Generated by Django 2.2 on 2019-04-26 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_auto_20190414_0043'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': '科系', 'verbose_name_plural': '科系'},
        ),
    ]
