# Generated by Django 2.2 on 2019-05-01 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_auto_20190426_1114'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, unique=True, verbose_name='群組名稱')),
            ],
            options={
                'verbose_name': '群組',
                'verbose_name_plural': '群組',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_no', models.CharField(max_length=15, unique=True, verbose_name='學號')),
                ('groups', models.ManyToManyField(to='school.Group', verbose_name='群組')),
            ],
            options={
                'verbose_name': '學生',
                'verbose_name_plural': '學生',
            },
        ),
    ]
