# Generated by Django 2.2.1 on 2019-05-07 04:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_auto_20190507_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='std_no',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator('(?P<night>[N|n]?)(?P<year>[0-9]{2,3})(?P<system>[1-9])(?P<department>[1-9A-Za-z])(?P<class>[0-9]?)(?P<no>[0-9]{2})', '不合法的學號')], verbose_name='學號'),
        ),
    ]
