# Generated by Django 2.2.1 on 2021-06-10 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_auto_20190507_1247'),
    ]

    operations = [
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, unique=True, verbose_name='學制名稱')),
            ],
            options={
                'verbose_name': '學制',
                'verbose_name_plural': '學制',
            },
        ),
    ]
